master:
  push:
    - imports: https://cnb.cool/Aurorxa/passkey/-/blob/main/envs.yml
      stages:
        - name: "🔧 构建当前项目 🔧 "
          image: node:24
          script: |
            npm install -g pnpm@10
            pnpm config set shamefully-hoist true
            pnpm config set public-hoist-pattern *
            pnpm install --no-frozen-lockfile
            pnpm run docs:build
        - name: 部署到 Pages
          image: node:24
          script: |
            npx edgeone@1.0.34 pages deploy ./docs/.vitepress/dist --name vitepress-web --token $EDGEONE_API_TOKEN